version: "3"

services:


  flask:


    build: ./flask

    container_name: flask

    restart: always

    environment: 
      - APP_NAME=MyFlaskApp

    expose:
      - 8080

    volumes:
      - ./log/uwsgi:/var/log/uwsgi
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"